name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # por si la cobertura no estuviera en requirements:
          python -m pip install coverage

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
          # Si tu entorno tiene el plugin de "spec", estos flags funcionarán.
          # Si llegara a fallar por flags desconocidos, usa la línea alternativa de abajo.
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
          # --- Alternativa si falla por flags desconocidos (quitar la línea de arriba y descomentar):
          # nosetests -v --with-coverage --cover-package=app
